name: qit
description: "A new assessment based ecommerce project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.9.2


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  http: ^1.5.0
  provider: ^6.1.5+1
  firebase_core: ^4.2.1
  firebase_auth: ^6.1.2
  cloud_firestore: ^6.1.0
  firebase_storage: ^13.0.4
  google_sign_in: ^6.2.1
  go_router: ^16.3.0
  image_picker: ^1.2.0
  file_picker: ^10.3.3
  get_it: ^9.0.5
  csv: ^6.0.0
  hive_flutter: ^1.1.0
  path_provider: ^2.1.5
  intl: ^0.20.2
  tuple: ^2.0.2
  flutter_rating_bar: ^4.0.0
  lottie: ^3.3.2
  change_app_package_name: ^1.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  web:
    generate: true
    image_path: "assets/images/app_icon.png"
  image_path: "assets/images/app_icon.png"
  adaptive_icon_background: "#FFB300"
  adaptive_icon_foreground: "assets/images/app_icon.png"


flutter:
  uses-material-design: true


  assets:
    - assets/
    - assets/images/



